<a href="https://colab.research.google.com/github/kimalaacer/Head-First-Learn-to-Code/blob/master/Tutorial4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
x = torch.arange(18).view(3,2,3)

In [0]:
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [0]:
x[1,1,1]

tensor(10)

In [0]:
x[2,1,2]

tensor(17)

In [0]:
x[1, 0:2,0:3]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [0]:
x[1, :,:]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])